#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 30 07:55:22 2020

@author: siddhesh
"""

import os
from argparse import ArgumentParser
import torch

if __name__ == "__main__":

    parser = ArgumentParser(description="Convert the .ckpt files to .pt files")
    parser.add_argument(
        "-i",
        "--input",
        dest="input",
        help="Input .ckpt file generated by lightning",
        required=True,
    )
    parser.add_argument(
        "-o",
        "--output",
        dest="output",
        help="Output .pt file to be generated, must be with extension of .pt",
        required=True,
    )
    args = parser.parse_args()

    ckpt_file = os.path.abspath(args.input)
    pt_file = os.path.abspath(args.output)

    print("Attempting to load file:", ckpt_file)
    with open(ckpt_file, "rb") as f:
        weight_load = torch.load(f, map_location=torch.device("cpu"))
    print("Load successful! Converting file.")
    new_state_dict = {}
    for key, value in weight_load["state_dict"].items():
        new_key = key[6:]
        new_state_dict[new_key] = value
    model_state_dict = {"model_state_dict": new_state_dict}
    print("Conversion successful!")
    with open(pt_file, "wb") as f:
        torch.save(model_state_dict, f)
    print("File saved successfully at:", pt_file)
